x = input ( "subject1 = " )
y = int ( x ) 
x = input ( "subject2 = " )
y = y + int ( x ) 
x = input ( "subject3 = " )
y = y + int ( x ) 
x = input ( "subject4 = " )
y = y + int ( x ) 
x = input ( "subject5 = " )
y = y + int ( x ) 
x = input ( "subject6 = " )
y = y + int ( x ) 
x = input ( "subject7 = " )
y = y + int ( x ) 
x = input ( "subject8 = " )
y = y + int ( x ) 
x = input ( "subject9 = " )
y = y + int ( x ) 
x = input ( "subject10 = " )
y = y + int ( x ) 
print(y)